[package]
name = "xdp-ebpf-tproxy-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-ebpf = "0.1.0"
aya-log-ebpf = "0.1.0"
xdp-ebpf-tproxy-common = { path = "../xdp-ebpf-tproxy-common" }
network-types = "0.0.4"

[[bin]]
name = "xdp-ebpf-tproxy"
path = "src/main.rs"

[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[workspace]
members = []
